### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by yedhukrishnan** [rautarchana9/Archana_Raut#1]
Hi @rautarchana9,

Sorry for the delay in getting back. Your solution looks promising. I liked the way you have modularised the code into multiple classes. The conventions followed while writing Python code is consistent.

I've a few questions and modifications for you. Here are they:

- I didn't get the significance of the name 'UserPref'. The problem is called 'Movie Aggregator' and I was confused by the name. It would be great if you can make the naming explicit and readable.

- I would like to know why the UserPref (which holds the movie information) class is inherited to UserPrefTxt and UserPrefPdf (which exports the data into different formats). Both the classes perform entirely different tasks.

- It's good that you have used reflection in your code. But we recommend you to use reflection to avoid changes to the existing codebase while adding new plugins. Can you please modify your code in such a way that, to add a new plugin, there shouldn't be a change to the existing code? It should be like **plug-and-play**: When you add a new export format class file, the application should detect and use it next time.

- It would be great if you can move different classes to different files.

Can you update your code with these modifications? Please reply with a date by when you can submit the modified solution.

**Comment by rautarchana9** [comment]
Thank you the valuable suggestions and feedback. 
a. The UserPref class is inherited to UserPrefTxt and UserPrefPdf, so that I didn't have to instantiate both classes separately. 
b. Yes I have modified the code as per the feedback.  All the different classes are now moved to different files under the folder called modules. Please follow the 5th commit on the repo to check the modifications.
https://github.com/rautarchana9/Archana_Raut/tree/a61256274f4e878d7f8876b6125ddaf8544bcb04
